[package]
name = "triggers-getting-started"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8.1"
http = "1.3.1"
hyper = { version = "0.14", features = ["http1"] }
